### ISSUE TITLE
Documentation says config_f instead of config

### ISSUE THREAD

**Issue by FlxVctr** [ryanjgallagher/focalevents#5]
Here: https://focalevents.readthedocs.io/en/latest/cookbook/twitter/search.html#search-parameters
should be config, at least as I read the code.

**Comment by ryanjgallagher** [comment]
I think `config_f` should be correct for the search parameters. In the code, `config` is the actual dictionary that gets read from the YAML file specified by `config_f`. 

Does that match your understanding of the code?

**Comment by ryanjgallagher** [comment]
Ah I see, the issue was with the parser argument name. Thank you!
